title:        "UPX"
tagline:      "the Ultimate Packer for eXecutables"
baseurl:      ""
paginate:     1
weburl:       https://upx.github.io

author:
  name:       The UPX Team
  url:        https://github.com/upx

exclude:
  - Makefile
  - README

gems:
  - jekyll-paginate
  - jekyll-redirect-from

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
